### ISSUE TITLE
Add and remove public holidays, Move events while taking into account holidays, weekends and time zone changes due to DST

### ISSUE THREAD

**Issue by Josehower** [upleveled/ical-move-events#3]
Moving all events kind of works, but requires manual work to move events to avoid holidays. In addition to this, some events should not be moved, which makes it more difficult to figure out how to rearrange the calendar.

Read a list of public holidays (via [the Google ICS files](https://calendar.teamup.com/kb/holiday-calendar-feeds-preview-teamup/) such as [Austria's](https://calendar.google.com/calendar/ical/en.austrian%23holiday%40group.v.calendar.google.com/public/basic.ics
))

and then:

1. remove the existing holiday entries which have been copied from the original iCalendar file (holiday entries marked with 🎉 emoji)
2. add new entries from the holiday iCalendar file with the 🎉 emoji

Also, while moving events, move each event one by one (creating the most compact schedule possible, as early as possible in the bootcamp), taking into consideration:

1. Weekends are blocked
2. The public holidays are blocked

For multi-day events (mostly projects currently):

Read the duration of the event from the title (eg. "(2 days)")

**Comment by karlhorky** [comment]
Sounds like a great feature!

**Comment by karlhorky** [comment]
Implementation TODOs:

- [ ] Accept an end date from the user
- [ ] Filter out all vacation days from events in the calendar
- [ ] Find the start date of the first event
- [ ] Create array of arrays of events (each inner array corresponds to the events starting on a particular day)
- [ ] Create an array of all available dates (dates that are not a weekend date or holiday date) between the start date of the first event and the end date specified by the user
- [ ] Loop over the array of arrays of events, modifying the start date to the next available date
  - [ ] Modify the end date of multi-day events
    - [ ] Shorten any multi-day events that end after the end date
  - [ ] Once all events have been modified, mark this available date as `scheduled`
  - [ ] Omit any events left over after all available dates are marked `scheduled`
  - [ ] Print a notice for events that were removed at the end of the range or shortened
